# V-监视器配置文件（V-Monitor Configuration）

# 插件基本设置（Plugin basic settings）
plugin-basic:
  # 默认语言设置（Default language settings）
  language:
    # 默认语言（Default language）
    # 支持的语言：zh_cn, zh_tw, en_us（Support language: zh_cn, zh_tw, en_us）
    default: "zh_cn"
  # 数据存储设置 (Data storage settings)
  data-storage:
    # 数据库类型（Database type）
    # 支持的类型：sqlite, mysql（Supported types: sqlite, mysql）
    type: "sqlite"
    # SQLite数据库配置（SQLite database configuration）
    sqlite:
      # SQLite数据库文件路径（SQLite database file path）
      path: "data.db"
    # MySQL数据库连接配置（MySQL connection configuration）
    mysql:
      # MySQL服务器地址（MySQL server address）
      host: "localhost"
      # MySQL服务器端口（MySQL server port）
      port: 3306
      # MySQL数据库名称（MySQL database name）
      database: "v_monitor"
      # MySQL数据库用户名（MySQL database username）
      username: "root"
      # MySQL数据库密码（MySQL database password）
      password: "password"
      # MySQL自定义参数配置（MySQL custom parameter configuration）
      # 参数格式为：数据库设置项: 值 （Parameter format: database setting item: value）
      # 示例（Example）：
      # parameters:
      #   useSSL: "false"
      parameters: []
    # HikariCP 数据库连接池配置（HikariCP database connection pool configuration）
    hikari:
      # 最大连接数（Maximum number of connections）
      maximum-pool-size: 32
      # 最小空闲连接数（Minimum idle connections）
      minimum-idle: 16
      # 连接超时时间（Connection timeout）
      # 单位：毫秒（Unit: milliseconds）
      connection-timeout: 30000
      # 空闲连接存活时间（Idle connection lifetime）
      # 单位：毫秒（Unit: milliseconds）
      idle-timeout: 600000
      # 最大生命周期（Maximum lifetime）
      # 单位：毫秒（Unit: milliseconds）
      max-lifetime: 1800000

# 服务器信息设置（Server info settings）
server-info:
  # 服务器名称（Server name）
  name: "My Velocity Server"
  # 服务器别名（Server aliases）
  # 参数格式为：实际服务器名称: "别名"（Parameter format: actual server name: "alias"）
  # 支持为多个服务器同时设置别名（Supports setting aliases for multiple servers at the same time）
  # 示例（Example）：
  # aliases:
  #   lobby: "hub"
  #   game: "minigames"
  aliases: []