# V-Monitor Configuration

# Configuration file version（配置文件版本）
version = "1.1"

# Default language（默认语言设置）
[language]
default = "zh_cn"

# Server aliases (服务器名称别名设置)
# Format: alias = "actual_server_name"
# Example: 'hub' will be an alias for the server named 'lobby'
# hub = "lobby"
# creative = "server2"
[server-aliases]
