# V-监视器配置文件（V-Monitor Configuration）

# 插件基本设置（Plugin basic settings）
plugin-basic:
  # 默认语言设置（Default language settings）
  language:
    # 默认语言（Default language）
    # 支持的语言：zh_cn, zh_tw, en_us（Support language: zh_cn, zh_tw, en_us）
    default: "zh_cn"

# 服务器信息设置（Server info settings）
server-info:
  # 服务器名称（Server name）
  name: "My Velocity Server"
  # 服务器别名（Server aliases）
  # 参数格式为：实际服务器名称: "别名"（Parameter format: actual server name: "alias"）
  # 支持为多个服务器同时设置别名（Supports setting aliases for multiple servers at the same time）
  # 示例（Example）：
  # aliases:
  #   lobby: "hub"
  #   game: "minigames"
  aliases: []